### ISSUE TITLE
drossel doesn't do russian

### ISSUE THREAD

**Issue by rio-** [tliff/schnapsdrossel#12]
posting a youtube-link to a russian video we get

    <d0k> https://www.youtube.com/watch?v=Vqxs7-8OUIc КСП
    <schnapsdrossel> YouTube: Ð Ð°ÐºÐµÑÐ½ÑÐµ ÑÑÐµÐ½Ð¸Ñ Ð Ð¾ÑÑÐ¸Ð¸! (02:16)

instead of `Ракетные учения России!`

**Comment by gix** [comment]
Fixed with 32bdf51130820857
