### ISSUE TITLE
Display video information for YouTube video links

### ISSUE THREAD

**Issue by raimue** [tliff/schnapsdrossel#6]
When someone posts a link to YouTube, print video title and length to the channel.

For starters, here is a regex to extract the video ID from URL: https?://(?:youtube\.com/watch\?v=([^/&]+)|youtu\.be/([^/]+)/?)

**Comment by tliff** [comment]
the drossel now displays the video title.

Do we need the length?

**Comment by rio-** [comment]
yes please

**Comment by maffe** [comment]
Case in protocol and hostname should be ignored.

**Comment by tliff** [comment]
Case is now ignored and the duration will be displayed
