### ISSUE TITLE
Show information for Spotify-HTTP-URLs

### ISSUE THREAD

**Issue by ddomhoff** [tliff/schnapsdrossel#8]
Since the new version of the Spotify-client does not provide spotify:-URLs anymore, it should display Information on artist, album name and title when someone pastes an HTTP-URL to open.spotify.com into the channel.

**Comment by tliff** [comment]
Fixed in https://github.com/tliff/schnapsdrossel/commit/1983a6814fda803e34f4440b6a15013bd439f988
